# Laboratorio 2 #

In [2]:
import numpy as np
import pandas as pd

## Problema 1 ##

In [3]:
# Copiamos el problema #
M = np.array([
    [1,1,0,0,0,0,1],
    [0,1,1,0,0,1,0],
    [0,0,1,1,0,0,0],
    [0,0,0,1,1,0,1],
    [1,0,0,0,0,1,1],
    [0,0,0,0,1,1,1],
    [1,1,1,0,0,0,1]])

M1 = np.array([
    [1,1,0,0,0,1,1],
    [1,1,1,0,1,0,0],
    [0,1,1,1,1,0,0],
    [0,0,1,1,0,0,1],
    [0,1,1,0,1,1,1],
    [1,0,0,0,1,1,1],
    [1,0,0,1,1,1,1]])

M2 = np.array([
    [1,1,0,0,0,0,0],
    [1,1,0,0,0,0,0],
    [0,0,1,1,0,0,0],
    [0,0,1,1,0,0,0],
    [0,0,0,0,1,1,1],
    [0,0,0,0,1,1,1],
    [0,0,0,0,1,1,1]])

In [16]:
# Creamos las funciones que definirán si una función es Reflexiva, Simétrica o Transitiva #
def ref (m):
    if (np.diagonal(m).sum() == m.shape[0]):
        print('Reflexiva')
    else: print('No Reflexiva')


def sim (m):
    if ((m == np.transpose(m)).all()):
        print('Simétrica')
    else: print('No Simétrica')


def trans(m):
    M = m.dot(m)
    M[M>=1] = 1
    if ((m==M).all()):
        print('Transitiva')
    else: print('No Transitiva')

In [14]:
# Buscamos si son Simétricas #
print(sim(M))
print(sim(M1))
print(sim(M2))

No Simétrica
None
Simétrica
None
Simétrica
None


In [15]:
# Buscamos si son Reflexivas #
print(ref(M))
print(ref(M1))
print(ref(M2))

No Reflexiva
None
Reflexiva
None
Reflexiva
None


In [17]:
# Buscamos si son Transitivas #
print(trans(M))
print(trans(M1))
print(trans(M2))

No Transitiva
None
No Transitiva
None
Transitiva
None


## Problema 2 ##

In [19]:
# Creamos la matriz A #
A = np.arange(5,9).reshape(2,2)
print(A)

[[5 6]
 [7 8]]


In [20]:
# Creamos la matriz B #
B = np.arange(-7,-1).reshape(2,3)
print(B)

[[-7 -6 -5]
 [-4 -3 -2]]


In [21]:
# Creamos la matriz C #
C = np.arange(4,14,3).reshape(2,2)
print(C)

[[ 4  7]
 [10 13]]


In [22]:
# Creamos la matriz D #
D = np.eye(2)
print(D)

[[1. 0.]
 [0. 1.]]


In [23]:
# Creamos la matriz E #
E = np.zeros(6).reshape(2,3)
print(E)

[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
# Juntamos todas las matrices (pero no ingresamos los valores directamente)#
parte_1 = np.hstack([A,D,E])
parte_2 = np.hstack([D,C,B])
H = np.vstack([parte_1, parte_2])
print(H)

[[ 5.  6.  1.  0.  0.  0.  0.]
 [ 7.  8.  0.  1.  0.  0.  0.]
 [ 1.  0.  4.  7. -7. -6. -5.]
 [ 0.  1. 10. 13. -4. -3. -2.]]


## Pregunta 3 ##

In [25]:
# Creamos la matriz que voltearemos #
A = np.arange(0,24).reshape(4,6)
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [27]:
# Rotamos la matriz 90 grados en dirección de las agujas del reloj #
def rota90(m):
    a = np.transpose(m)
    print('Rotado 90 grados \n', np.flip(a,0))

rota90(A)

Rotado 90 grados 
 [[ 5 11 17 23]
 [ 4 10 16 22]
 [ 3  9 15 21]
 [ 2  8 14 20]
 [ 1  7 13 19]
 [ 0  6 12 18]]


In [28]:
# Rotamos la matriz 180 grados en dirección de las agujas del reloj #
def rota180(m):
    a = np.flip(m)
    print('Rotado 180 grados \n', a)

rota180(A)

Rotado 180 grados 
 [[23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]


In [31]:
# Rotamos la matriz 270 grados en dirección de las agujas del reloj #
def rota270(m):
    a = np.flip(m,0)
    print('Rotado 270 grados \n', np.transpose(a))

rota270(A)

Rotado 270 grados 
 [[18 12  6  0]
 [19 13  7  1]
 [20 14  8  2]
 [21 15  9  3]
 [22 16 10  4]
 [23 17 11  5]]


In [32]:
# Rotamos la matriz 90 grados en dirección contraria de las agujas del reloj #
def rota90_otro_lado(m):
    a = np.transpose(m)
    print('Rotado 90 Grados Rotados \n', np.flip(a,1))

rota90_otro_lado(A)

Rotado 90 Grados Rotados 
 [[18 12  6  0]
 [19 13  7  1]
 [20 14  8  2]
 [21 15  9  3]
 [22 16 10  4]
 [23 17 11  5]]


In [33]:
# Rotamos la matriz 180 grados en dirección contraria de las agujas del reloj #
def rota180_otro_lado(m):
    a = np.flip(m)
    print('Rotado 180 Grados Rotado \n', a)

rota180_otro_lado(A)

Rotado 180 Grados Rotado 
 [[23 22 21 20 19 18]
 [17 16 15 14 13 12]
 [11 10  9  8  7  6]
 [ 5  4  3  2  1  0]]


In [34]:
# Rotamos la matriz 270 grados en dirección contraria de las agujas del reloj #
def rota270_otro_lado(m):
    a = np.transpose(m)
    print('Rotado 270 Grados Rotado \n', np.flip(a,0))

rota270_otro_lado(A)

Rotado 270 Grados Rotado 
 [[ 5 11 17 23]
 [ 4 10 16 22]
 [ 3  9 15 21]
 [ 2  8 14 20]
 [ 1  7 13 19]
 [ 0  6 12 18]]


### Problema 4 ###

In [37]:
# En primer lugar copiamos el sistema de ecuaciones #
sistema_de_ecuaciones = np.array([
[2,0,0,1,0,0,0,0],
[1,0,0,1,0,0,0,0],
[-1,0,0,2,0,0,0,0],
[0,2,0,0,1,0,0,0],
[0,1,0,0,1,0,0,0],
[0,-1,0,0,2,0,0,0],
[0,0,2,0,0,1,0,0],
[0,0,1,0,0,1,0,0],
[0,0,-1,0,0,2,0,0],
[0,0,0,0,0,0,1,2],
[0,0,0,0,0,0,1,1],
[0,0,0,0,0,0,2,-1]
])

In [38]:
# Ahora copiamos la respuesta de los sistemas de ecuaciones #
respuestas = np.array([
    [4],
    [3],
    [3],
    [3],
    [2],
    [1],
    [6],
    [4],
    [2],
    [-3],
    [-1],
    [4]
])

In [43]:
# Ahora obtenemos las respuestas a las variables #
solucion = np.matmul(np.linalg.pinv(sistema_de_ecuaciones), respuestas)
solucion

array([[ 1.],
       [ 1.],
       [ 2.],
       [ 2.],
       [ 1.],
       [ 2.],
       [ 1.],
       [-2.]])